### PR TITLE
new updates to include year

### PR DESCRIPTION
**Pull request by acircleda**
I updated the function to allow a year argument and processed data for years 2019-2024 in a consistent manor. Also some minor updates.

### CODE REVIEW

**Review by KKulma — APPROVED** [review]
The changes look good, CI pipeline failed on the mac container but it looks like it's to do with the definition of the pipeline rather than errors in the package, so I'm happy to approve the PR 👍

**Comment by acircleda** [comment]
> The changes look good, CI pipeline failed on the mac container but it looks like it's to do with the definition of the pipeline rather than errors in the package, so I'm happy to approve the PR 👍

I'll update the Github workflow to see of that fixes it.

**Comment by acircleda** [comment]
Fixed the CI job, merged, and re-submitted to CRAN.
Thanks!

**Comment by acircleda** [comment]
@KKulma Just an update from CRAN:

> Your package footprint_0.2.tar.gz has been built for Windows and will be published within 24 hours in the corresponding CRAN directory. R version 4.4.1 (2024-06-14 ucrt)

**Pull request merged**
